select 'auth.users=' || count(*) from auth.users
union all select 'auth.identities=' || count(*) from auth.identities
union all select 'public.account_profiles=' || count(*) from public.account_profiles
union all select 'public.account_settings=' || count(*) from public.account_settings
union all select 'public.user_entitlements=' || count(*) from public.user_entitlements
union all select 'public.guest_identities=' || count(*) from public.guest_identities
union all select 'public.quota_plans=' || count(*) from public.quota_plans
union all select 'public.quota_plan_limits=' || count(*) from public.quota_plan_limits
union all select 'public.usage_counters=' || count(*) from public.usage_counters
union all select 'public.usage_actions=' || count(*) from public.usage_actions
union all select 'public.usage_executions=' || count(*) from public.usage_executions
union all select 'public.user_data_objects=' || count(*) from public.user_data_objects
union all select 'public.admin_audit_logs=' || count(*) from public.admin_audit_logs
union all select 'public.public_articles=' || count(*) from public.public_articles
union all select 'public.public_explanations=' || count(*) from public.public_explanations
union all select 'public.public_article_translations=' || count(*) from public.public_article_translations
union all select 'storage.buckets=' || count(*) from storage.buckets
union all select 'storage.objects=' || count(*) from storage.objects;
