import { createRequire } from "node:module";
import test from "node:test";
import assert from "node:assert/strict";
import { JSDOM } from "jsdom";
import { IDBFactory } from "fake-indexeddb";
import * as React from "react";
import type { CetPaper } from "../types/cet";

test("developer edits the real passage, saves immediately, preserves history and retries conflicts", async () => {
  const dom = new JSDOM("<!doctype html><body></body>", { url: "https://context-reader.com", pretendToBeVisual: true });
  Object.assign(globalThis, { IS_REACT_ACT_ENVIRONMENT: true });
  for (const [key, value] of Object.entries({ window: dom.window, document: dom.window.document, navigator: dom.window.navigator, HTMLElement: dom.window.HTMLElement, CustomEvent: dom.window.CustomEvent, Event: dom.window.Event, React, requestAnimationFrame: dom.window.requestAnimationFrame.bind(dom.window), cancelAnimationFrame: dom.window.cancelAnimationFrame.bind(dom.window), getComputedStyle: dom.window.getComputedStyle.bind(dom.window) })) Object.defineProperty(globalThis, key, { configurable: true, value });
  Object.defineProperty(dom.window, "indexedDB", { value: new IDBFactory() });
  dom.window.matchMedia = (query: string) => ({ matches: false, media: query, onchange: null, addListener() {}, removeListener() {}, addEventListener() {}, removeEventListener() {}, dispatchEvent: () => true });
  dom.window.scrollTo = () => {};
  dom.window.HTMLElement.prototype.scrollIntoView = () => {};
  Object.defineProperty(globalThis, "IntersectionObserver", { configurable: true, value: class { observe() {} disconnect() {} } });
  const require = createRequire(import.meta.url);
  require.extensions[".css"] = module => { module.exports = {}; };
  const mock = (path: string, exports: object) => { const filename = require.resolve(path); require.cache[filename] = { id: filename, filename, loaded: true, exports } as NodeModule; };
  mock("../components/AccountProvider", { useAccount: () => ({ account: { authenticated: true, profile: { userId: "developer" } }, isOffline: false }) });
  mock("../components/ReaderView", { ReaderView: ({ examSurface }: { examSurface: { rail: React.ReactNode; render: (lookup: () => void) => React.ReactNode } }) => <>{examSurface.rail}{examSurface.render(() => {})}</> });
  const { CetReader } = await import("../components/cet/CetReader");
  const { readCetActivities } = await import("../lib/cetActivityStorage");
  const { getLearningStorage, isLearningStorage } = await import("../lib/learningStorage");
  const { render, waitFor, cleanup, fireEvent } = await import("@testing-library/react");
  const { default: userEvent } = await import("@testing-library/user-event");
  const { writeCetEditableParagraphs } = await import("../lib/cetPaperFormatting");
  const paper: CetPaper = { id: "cet4-2025-12-1", level: 4, year: 2025, month: 12, set: 1, title: "编辑验证", source: "https://example.com", status: "ready", sections: [{ id: "detail-1", type: "detail", title: "仔细阅读", paragraphs: ["The first sentence. The second sentence."], questions: [{ number: 46, stem: "Why?", options: [{ key: "A", text: "Because." }], answer: "A" }] }] };
  let revision: string | null = null, patches = 0, conflict = false;
  const oldFetch = globalThis.fetch;
  globalThis.fetch = async (input, init) => {
    if (String(input) === "/api/admin/session") return Response.json({ accessMode: "developer" });
    if (init?.method === "PATCH") {
      patches++;
      const body = JSON.parse(String(init.body));
      assert.equal(body.expectedRevision, revision);
      if (conflict) return Response.json({ error: "此题已由另一处更新，请重新载入后再编辑。" }, { status: 409 });
      paper.sections[0].paragraphs = body.paragraphs; revision = `revision-${patches}`;
      return Response.json({ ok: true, revision });
    }
    return Response.json({ paper: structuredClone(paper), revision });
  };
  const noop = () => {};
  const props = { entry: { paperId: paper.id }, onOpen: noop, onBack: noop, savedArticles: [], onArticleSaved: noop, onOpenSavedArticle: noop, onRenameSavedArticle: noop, onDeleteSavedArticle: noop, onOpenImportedArticle: () => true };
  let ui = render(<CetReader {...props} />);
  const user = userEvent.setup({ document: dom.window.document });
  try {
    await user.click(await ui.findByRole("button", { name: "开始练习" }));
    await user.click(await ui.findByRole("button", { name: "编辑真题排版" }));
    const editable = await ui.findByRole("textbox", { name: "真题原文排版" });
    await waitFor(() => assert.equal(editable.getAttribute("contenteditable"), "true"));
    assert.equal(ui.queryByRole("dialog"), null);
    assert.equal(ui.container.querySelector("textarea"), null);
    assert.ok(editable.closest(".cet-reading"));
    const paragraphs = ["The first sentence.", "", "The second\nsentence."];
    writeCetEditableParagraphs(editable, paragraphs); fireEvent.input(editable);
    await user.click(ui.getByRole("button", { name: "保存排版" }));
    await waitFor(() => assert.ok(ui.getByText("排版已保存，当前原文已更新。")));
    await user.click(ui.getByRole("button", { name: "撤销" }));
    assert.equal(editable.textContent, "The first sentence. The second sentence.");
    await user.click(ui.getByRole("button", { name: "重做" }));
    assert.equal(ui.getByRole("button", { name: "保存排版" }).hasAttribute("disabled"), true);
    await user.click(ui.getByRole("button", { name: "完成编辑" }));
    assert.deepEqual(Array.from(ui.container.querySelectorAll(".cet-passages > p")).map(p => p.textContent), paragraphs);
    const answers = JSON.stringify(readCetActivities()[0].answers);
    await user.click(await ui.findByRole("button", { name: "编辑真题排版" }));
    const second = await ui.findByRole("textbox", { name: "真题原文排版" });
    await waitFor(() => assert.equal(second.getAttribute("contenteditable"), "true"));
    writeCetEditableParagraphs(second, ["The first sentence.", "The second sentence."]); fireEvent.input(second);
    conflict = true;
    await user.click(ui.getByRole("button", { name: "保存排版" }));
    await waitFor(() => assert.ok(ui.getByText(/此题已由另一处更新/)));
    assert.equal(second.textContent, "The first sentence.The second sentence.");
    assert.equal(JSON.stringify(readCetActivities()[0].answers), answers);
    await user.click(ui.getByRole("button", { name: "完成编辑" }));
    assert.ok(ui.getByText("有尚未保存的修改。"));
    await user.click(ui.getByRole("button", { name: "放弃修改" }));
    assert.deepEqual(Array.from(ui.container.querySelectorAll(".cet-passages > p")).map(p => p.textContent), paragraphs);
    const attemptId = readCetActivities()[0].id;
    cleanup();
    ui = render(<CetReader {...props} entry={{ paperId: paper.id, attemptId }} />);
    await waitFor(() => assert.deepEqual(Array.from(ui.container.querySelectorAll(".cet-passages > p")).map(p => p.textContent), paragraphs));
    cleanup();
    const { createCetActivity, cetFinalize } = await import("../lib/cetActivity");
    const { addCetUnderlines } = await import("../lib/cetUnderlines");
    const { saveCetActivity } = await import("../lib/cetActivityStorage");
    const originalPaper = structuredClone(paper);
    let old = createCetActivity({ paper: originalPaper, purpose: "self_test", owner: readCetActivities()[0].owner, timerMode: "countup" });
    old = addCetUnderlines(old, originalPaper, [{ sectionId: "detail-1", paragraphIndex: 0, start: 0, end: 3 }], "blue");
    old = saveCetActivity(cetFinalize(old, originalPaper, "manual_submit"));
    const frozen = JSON.stringify(old.finalizations);
    paper.sections[0].paragraphs = ["The first sentence. The second sentence."];
    ui = render(<CetReader {...props} entry={{ paperId: paper.id, attemptId: old.id }} />);
    await waitFor(() => assert.deepEqual(Array.from(ui.container.querySelectorAll(".cet-passages > p")).map(p => p.textContent), paragraphs));
    await user.click(await ui.findByRole("button", { name: "编辑真题排版" }));
    const historicalEditor = await ui.findByRole("textbox", { name: "真题原文排版" });
    await waitFor(() => assert.equal(historicalEditor.getAttribute("contenteditable"), "true"));
    conflict = false;
    writeCetEditableParagraphs(historicalEditor, ["The first sentence.", "The second sentence."]); fireEvent.input(historicalEditor);
    await user.click(ui.getByRole("button", { name: "保存排版" }));
    await waitFor(() => assert.ok(ui.getByText("排版已保存，当前原文已更新。")));
    await user.click(ui.getByRole("button", { name: "完成编辑" }));
    assert.equal(ui.container.querySelectorAll(".cet-passages > p").length, 2);
    assert.equal(ui.container.querySelectorAll(".cet-passages [data-cet-underline-id]").length, 0);
    assert.equal(JSON.stringify(readCetActivities().find(a => a.id === old.id)?.finalizations), frozen);
  } finally {
    cleanup(); globalThis.fetch = oldFetch;
    const storage = getLearningStorage(); if (isLearningStorage(storage)) storage.close();
    dom.window.close();
  }
});
