-- Run only in context_reader_study_1005 (a restored backup), never production.
begin;
do $$
declare u uuid:=gen_random_uuid(); v uuid:=gen_random_uuid(); review_id uuid:=gen_random_uuid(); token uuid;
 c text:='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'; r jsonb; m jsonb; original jsonb; n integer;
begin
 assert current_database()='context_reader_study_1005','isolated database required';
 insert into auth.users(id) values(u),(v);
 insert into account_profiles(user_id,nickname,status) values(u,'study-test','active'),(v,'study-other','active') on conflict(user_id) do update set status='active';
 insert into user_entitlements(user_id,plan_id,source) values(u,'free','signup'),(v,'free','signup') on conflict(user_id) do update set plan_id='free';
 original:=jsonb_build_object('due',now(),'stability',0,'difficulty',0,'elapsed_days',0,'scheduled_days',0,'reps',0,'lapses',0,'state',0,'learning_steps',0);
 insert into study_cards(user_id,id,entry_id,mode,memory) values(u,c,'entry','cloze_context',original);
 perform study_start(u,to_jsonb(array[c]),'{"retention":0.9}');
 r:=study_present(u,c,0);token:=(r->>'token')::uuid;assert token is not null,'presentation exists';
 assert study_present(v,c,0)->>'conflict'='true','another owner cannot present';
 r:=study_review(u,review_id,c,0,token,'unsure_wrong',1,1000,original,'FSRS-6','{}');assert r->>'tooFast'='true','server bounds rapid submissions';
 update study_cards set shown_at=now()-interval '2 seconds' where user_id=u;
 m:=original||jsonb_build_object('due',now()+interval '1 minute','last_review',now(),'state',1,'reps',1,'stability',0.2);
 r:=study_review(u,review_id,c,0,token,'unsure_wrong',1,5000,m,'FSRS-6','{}');assert r->>'saved'='true','save forgotten outcome';
 assert (select active_ms from study_reviews where user_id=u and study_reviews.id=review_id)=2000,'foreground time cannot exceed server elapsed time';
 r:=study_review(u,review_id,c,0,token,'unsure_wrong',1,5000,m,'FSRS-6','{}');assert r->>'duplicate'='true','idempotent network retry';
 assert (select count(*) from study_reviews where user_id=u)=1,'one durable event';
 r:=study_review(u,gen_random_uuid(),c,0,token,'remembered',3,2000,m,'FSRS-6','{}');assert r->>'conflict'='true','stale other device rejected';
 r:=study_complete(u);assert r->>'complete'='false','learning is not complete';
 r:=study_undo(u,review_id);assert r->>'saved'='true','undo restores prior state';
 assert (select memory from study_cards where user_id=u)=original,'exact memory restoration';
 r:=study_undo(u,review_id);assert r->>'duplicate'='true','undo retry idempotent';
 assert (select undone from study_reviews where user_id=u),'history retained as undone';
 insert into study_settings(user_id,settings) values(u,jsonb_build_object('pausedUntil',now()+interval '3 days'));
 r:=study_review(u,gen_random_uuid(),c,2,token,'remembered',3,2000,m,'FSRS-6','{}');assert r->>'paused'='true','pause checked inside transaction';
 update study_settings set settings='{}' where user_id=u;
 r:=study_present(u,c,2);token:=(r->>'token')::uuid;
 update study_cards set shown_at=now()-interval '3 seconds' where user_id=u;
 m:=original||jsonb_build_object('due',now()+interval '3 days','last_review',now(),'state',2,'reps',2,'stability',3);
 r:=study_review(u,gen_random_uuid(),c,2,token,'remembered',3,1800,m,'FSRS-6','{}');assert r->>'saved'='true','review commits after resume';
 update study_policy set policy=policy||'{"rewardsEnabled":true,"pointsPerNew":1,"streakMinNew":5,"dailyRewardCap":10,"rewardDays":30}'::jsonb where study_policy.id;
 r:=study_complete(u);assert r->>'complete'='true' and (r->>'points')::int=1,'completed unique words earn proportional reward';
 assert (billing_balance(u)->>'allowance')::bigint=301,'real billing allowance credited';
 r:=study_complete(u);assert r->>'duplicate'='true','daily completion idempotent';
 assert (billing_balance(u)->>'allowance')::bigint=301,'no duplicate reward';
 assert (billing_balance(v)->>'allowance')::bigint=300,'account isolation';
 r:=study_daily_stats(u);assert jsonb_array_length(r)=1 and (r->0->>'cards')::int=1 and (r->0->>'reviews')::int=1,'undone events excluded from stats';
 perform study_reading_tick(u,30,'["Bank","bank","in spite of"]','article');
 assert (select jsonb_array_length(words) from study_reading_days where user_id=u)=2,'unique normalized reading observations';
 assert (select active_seconds from study_reading_days where user_id=u)=0,'first heartbeat cannot fabricate elapsed time';
 r:=study_profile_claim(u,review_id);assert r->>'claimed'='true','generation lease acquired';
 r:=study_profile_claim(u,gen_random_uuid());assert r->>'claimed'='false','concurrent model requests do not double spend';
 perform study_profile_release(u,gen_random_uuid());assert exists(select 1 from study_profile_jobs where user_id=u),'wrong action cannot release a lease';
 perform study_profile_release(u,review_id);assert not exists(select 1 from study_profile_jobs where user_id=u),'owner action releases';
 assert not has_table_privilege('anon','study_cards','select'),'anonymous cannot read progress';
 assert not has_table_privilege('authenticated','study_reviews','insert'),'browser cannot forge reviews';
 assert not has_function_privilege('authenticated','study_complete(uuid)','execute'),'browser cannot mint reward';
 raise notice 'PASS study: FSRS event persistence, ownership, replay, stale device, timers, undo, pause, rewards, reading, model lease, RLS';
end $$;
rollback;
