"use client";
import { useEffect, useState } from "react";
import type { BillingPlan, BillingOrder } from "@/lib/billingStore";
export function AdminBillingPanel() {
 const [plans,setPlans]=useState<BillingPlan[]>([]);const [orders,setOrders]=useState<BillingOrder[]>([]);
 const [ready,setReady]=useState(false);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch("/api/admin/billing",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setPlans(d.plans);setOrders(d.orders);setReady(d.paymentReady);}catch{setMessage("付费管理读取失败，请重试。");}}
 useEffect(()=>{void load();},[]);
 async function save(body:object){setBusy(true);setMessage("");try{const r=await fetch("/api/admin/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage("已保存。");await load();}catch(e){setMessage(e instanceof Error?e.message:"保存失败。");}finally{setBusy(false);}}
 function edit(id:string,key:keyof BillingPlan,value:number|boolean){setPlans(ps=>ps.map(p=>p.id===id?{...p,[key]:value}:p));}
 return <section className="rounded-2xl bg-white p-6 text-[#222]"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-2xl font-semibold">付费与套餐</h2><p className="mt-2 text-sm text-[#68717a]">微信支付：{ready?"已配置，开放下单":"尚未开放"} · 一次性购买，不自动扣款</p></div><button type="button" onClick={()=>void load()}>刷新</button></div>
 <p className="mt-5 text-sm leading-6">价格单位为人民币分。点数和价格保存后，付费页重新读取即生效；已生成订单和已发放额度保留原快照，下一会员月使用新点数。</p>
 <div className="mt-5 grid gap-4 md:grid-cols-2">{plans.map(p=><fieldset key={p.id} className="rounded-xl border p-4"><legend className="px-2 font-semibold">{p.name}</legend><div className="grid grid-cols-3 gap-3">{([["monthlyFen","月价（分）"],["annualFen","年价（分）"],["points","每月点数"]] as const).map(([key,label])=><label key={key} className="text-xs">{label}<input type="number" min="0" step="1" disabled={p.id==="free"&&key!=="points"} value={p[key]} onChange={e=>edit(p.id,key,Number(e.target.value))} className="mt-2 w-full rounded border p-2 text-sm"/></label>)}</div><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" disabled={p.id==="free"} checked={p.active} onChange={e=>edit(p.id,"active",e.target.checked)}/>开放新购</label><button type="button" disabled={busy} className="mt-4 rounded bg-[#263b32] px-4 py-2 text-sm text-white" onClick={()=>void save({action:"plan",planId:p.id,...p})}>保存 {p.name}</button></fieldset>)}</div>
 {message&&<p role="status" className="mt-5 text-sm">{message}</p>}
 <h3 className="mt-10 text-xl font-semibold">最近 100 笔订单</h3><p className="mt-2 text-xs text-[#68717a]">异常已付款但未发放权益的订单，可原路退还。正常已履约订单需人工核对剩余权益后通过微信商户平台处理；不要直接改订单状态。</p>
 <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr>{["订单 / 用户","套餐","实付 / 抵扣","点数","状态","操作"].map(t=><th key={t} className="p-3">{t}</th>)}</tr></thead><tbody>{orders.map(o=><tr key={o.id} className="border-t"><td className="p-3"><p>{o.id}</p><p className="mt-1 text-[#777]">{o.user_id}</p></td><td>{o.plan_id} · {o.term} · {o.kind}</td><td>¥{(o.amount_fen/100).toFixed(2)} / ¥{(o.credit_fen/100).toFixed(2)}</td><td>{o.points}</td><td>{o.status}{o.review_reason&&<p className="max-w-48 text-red-700">{o.review_reason}</p>}</td><td>{o.status==="pending"&&<button type="button" disabled={busy||!ready} onClick={()=>void save({action:"check_payment",orderId:o.id})}>核对微信支付状态</button>}{o.status==="review"&&<button type="button" disabled={busy} className="text-red-700 underline" onClick={()=>void save({action:"refund_review",orderId:o.id})}>原路全额退款</button>}{o.status==="refunding"&&<button type="button" disabled={busy} onClick={()=>void save({action:"check_refund",orderId:o.id})}>确认退款状态</button>}</td></tr>)}</tbody></table>{orders.length===0&&<p className="py-8 text-sm text-[#777]">还没有订单。</p>}</div>
 </section>;
}
